### ISSUE TITLE
Stellar Explorer Unhandled Error

### ISSUE THREAD

**Issue by zhaoshike** [orbitlens/stellar-expert-explorer#274]
Keep getting this with everything I open

"fffff" at https://stellar.expert/explorer/public/asset/XLM
Error: fffff
    at De (https://stellar.expert/distr/explorer.js:1:147836)
    at Zi (https://stellar.expert/distr/app.js?v=0.15.9:2:521759)
    at Es (https://stellar.expert/distr/app.js?v=0.15.9:2:567809)
    at yu (https://stellar.expert/distr/app.js?v=0.15.9:2:560551)
    at mu (https://stellar.expert/distr/app.js?v=0.15.9:2:560476)
    at su (https://stellar.expert/distr/app.js?v=0.15.9:2:557506)
    at https://stellar.expert/distr/app.js?v=0.15.9:2:509147
    at t.unstable_runWithPriority (https://stellar.expert/distr/app.js?v=0.15.9:2:584203)
    at Qo (https://stellar.expert/distr/app.js?v=0.15.9:2:508856)
    at Yo (https://stellar.expert/distr/app.js?v=0.15.9:2:509092)

**Comment by s-a-y** [comment]
Getting the same error for an account
https://stellar.expert/explorer/public/account/GCL5ZDPP4YWKBLFAYIQHZSHP63KHWPI6L4O2F7TQ5V27UKQDEWWKHZIU
```
"fffff" at https://stellar.expert/explorer/public/account/GCL5ZDPP4YWKBLFAYIQHZSHP63KHWPI6L4O2F7TQ5V27UKQDEWWKHZIU
Error: fffff
    at De (https://stellar.expert/distr/explorer.js:1:147836)
    at Zi (https://stellar.expert/distr/app.js?v=0.15.9:2:521759)
    at Es (https://stellar.expert/distr/app.js?v=0.15.9:2:567809)
    at yu (https://stellar.expert/distr/app.js?v=0.15.9:2:560551)
    at mu (https://stellar.expert/distr/app.js?v=0.15.9:2:560476)
    at su (https://stellar.expert/distr/app.js?v=0.15.9:2:557506)
    at https://stellar.expert/distr/app.js?v=0.15.9:2:509147
    at t.unstable_runWithPriority (https://stellar.expert/distr/app.js?v=0.15.9:2:584203)
    at Qo (https://stellar.expert/distr/app.js?v=0.15.9:2:508856)
    at Yo (https://stellar.expert/distr/app.js?v=0.15.9:2:509092)
```

**Comment by orbitlens** [comment]
Sorry about that, guys. The system update we rolled recently gone wrong.
Fixed now.
